cask_args appdir: "/Applications"

tap "homebrew/bundle"
brew "openssl@3"
brew "readline"
brew "curl"
brew "git"
brew "coreutils"
brew "asdf"
brew "direnv"
brew "gh"
brew "sqlite"
brew "tcl-tk"
brew "tree"
brew "xz"
brew "zlib"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-git-prompt"
brew "zsh-syntax-highlighting"
brew "awscli"
brew "aws-sam-cli"
brew "jq"
brew "volta"
brew "mysql"

# Desktop Apps
cask "visual-studio-code"
cask "google-chrome"
cask "iterm2"
cask "docker"
cask "postman"
cask "slack"
cask "discord"
cask "zoom"
